#!/usr/bin/env zsh
# vi: set expandtab ft=zsh tw=80 ts=2

function getExecPrerequisites() {
  cmds+=(
    [mkdir]=''
  )
}

function hideFolders() {
  chflags hidden ${HOME}/{bin,dotfiles}
}

function configure_system() {
  local dirPath
  for dirPath in ${HOME}/bin ${HOME}/.vim/{backups,swaps}; do
    [[ ! -d ${dirPath} ]] && indicateActivity mkdir,${dirPath} "Creating ${dirPath}"
  done
  indicateActivity hideFolders 'Hide folders'
}


if [[ "${ZSH_EVAL_CONTEXT}" == toplevel ]]; then
  source ../lib.sh || exit
  app_main "$@"
fi
